### ISSUE TITLE
Improvement: Ask the user if they would like to install .NET 6.0 in installer

### ISSUE THREAD

**Issue by Shoreasg** [otherdeniz/Zilliqa.DesktopWallet#3]
As a user, i would like to be asked to download .NET 6.0 / any necessary dependency for me when i use the installer

**Comment by otherdeniz** [comment]
please read the following release comment

**Release for Windows 64 bit
Requires: .NET Desktop Runtime 6.0 - download from microsoft [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-x64-installer)**

and then click on the "here" text

there is the possibility to provide an "setup.exe" that does this for you - but then i have to provide a second release file in ZIP-format, wich includes the "msi" and the "setup.exe" ....

please tell me, would you prefer to have 2 downloads on each release available?
- 1st - only the "msi"
- 2nd - a zip file containing the "msi" and the "setup.exe" which does the pre-installation requirements setup for the user?

i can add this second option, if you think its helpfull

please respond with your choice

**Comment by otherdeniz** [comment]
please see the newest release v0.45
i have included a setup zip file this time, can you please check it out

thanks for feedback

**Comment by Shoreasg** [comment]
Hello! The 2nd option is the best and after installing setup.exe, everything is working for me now! I would suggest you keep this option as i am worried not tech savvy users would not understand what and how to install other dependency.

I will close this issue!
