### ISSUE TITLE
After installing .NET 6.0, I am unable to proceed

### ISSUE THREAD

**Issue by Shoreasg** [otherdeniz/Zilliqa.DesktopWallet#4]
After installing .NET 6.0, i am prompt to install missing framework for .NET.

Clicking yes does not do anything.

Things i tried:

1. Repair using ZilliqaDesktopWallet.msi
2. Repiar using dotnet-runtime
3. Restart Computer

Image:

[Image](https://imgur.com/fzS91hY)

**Comment by otherdeniz** [comment]
did you install the correct .NET 6.0 Desktop Runtime ? or only the .NET 6 runtime
it needs the Desktop Runtime !
"dotnet-runtime" is not enough, please use the full ".NET 6 Desktop Runtime" its more than just the basic runtime

**Comment by Shoreasg** [comment]
This is solved after using setup.exe!
