### ISSUE TITLE
Improvement: Allow user to choose to create a new wallet or connect an existing wallet

### ISSUE THREAD

**Issue by Shoreasg** [otherdeniz/Zilliqa.DesktopWallet#6]
When i first open the app, i am prompt to create a wallet. 

As an existing user, i would like to be asked if i want to create a new wallet OR connect an existing one.

[prompt](https://imgur.com/8WgSJoQ)

**Comment by otherdeniz** [comment]
- create new wallet on first startup is now optional, if the user creates wallet, he can choose to create new or import private key / this feature is implemented in the upcoming version 0.46
- Connect "Ledger Hardware wallet" support is ongoing, its coming soon. Actually, there is no working reference implementation in C# available, i have to implement it based on Ledger Bitcoin C# implementation, this will take longer than expected.

**Comment by otherdeniz** [comment]
eventually you can ask the community if there is any working Ledger Zilliqa C# refference code available, it would help me a lot.
would you do a little research in the community in this regard?

**Comment by otherdeniz** [comment]
Connect "Ledger Hardware wallet" support is completed.
This feature is available in version 0.47
